### ISSUE TITLE
TypeScript errors when upgrading from 2.x to 3.x

### ISSUE THREAD

**Issue by lenovouser** [ekalinin/sitemap.js#193]
```
node_modules/sitemap/dist/lib/sitemap-item.d.ts:1:8 - error TS1259: Module '"node_modules/xmlbuilder/typings/index"' can only be default-imported using the 'esModuleInterop' flag

1 import builder from 'xmlbuilder';
         ~~~~~~~

  node_modules/xmlbuilder/typings/index.d.ts:4:1
    4 export = xmlbuilder;
      ~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```

**Comment by derduher** [comment]
It looks like xmlbuilder incorrectly defines its default export but this has been addressed by only importing sub objects. This should be fixed in master.

**Comment by lenovouser** [comment]
@derduher I tried `3.2.0` and it now fails with two errors:

```
node_modules/sitemap/dist/lib/sitemap.d.ts:6:8 - error TS1192: Module '"zlib"' has no default export.

6 import zlib from 'zlib';
         ~~~~

node_modules/sitemap/dist/lib/types.d.ts:1:8 - error TS1259: Module '"node_modules/xmlbuilder/typings/index"' can only be default-imported using the 'esModuleInterop' flag

1 import builder from 'xmlbuilder';
         ~~~~~~~

  node_modules/xmlbuilder/typings/index.d.ts:4:1
    4 export = xmlbuilder;
      ~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.


Found 2 errors.

 ERROR  Command failed with exit code 1.
```

**Comment by derduher** [comment]
@lenovouser I think I got it fixed this time. Do you mind giving master a try?

**Comment by lenovouser** [comment]
@derduher yes, master doesn't fail for me anymore 🚀

**Comment by derduher** [comment]
released in 3.2.1
